app = "your-app-name" # Replace with your app name

[build]
  builder = "heroku/buildpacks:20" # Choose an appropriate builder for your project

[env]
  ALLOW_EOL_SHIMMED_BUILDER = "1"

[[services]]
  [services.http] # This is the correct way to define the HTTP service
    internal_port = 8080
    auto_rollback = true
