app = "shkolo-assignment" # Replace with your app name

kill_signal = "SIGINT"
kill_timeout = 5

# Use the Cloud Native Buildpack for PHP
builder = "heroku/php"

[[services]]
  http_service = {
    internal_port = 8080
    auto_rollback = true
  }
