app = "shkolo-assignment" # Replace with your app name

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:24" # Using the current stable builder

[[services]]
  [http_service]
    internal_port = 8080
    auto_rollback = true
