app = "your-app-name" # Replace with your app name

[build]
  builder = "heroku/buildpacks:latest" # Choose an appropriate builder for your project

[[services]]
  [services.http] # This is the correct way to define the HTTP service
    internal_port = 8080
    auto_rollback = true
